# Generated by Django 3.2.5 on 2021-08-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_location',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='doctor_location',
            old_name='createBy',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='doctor_location',
            old_name='updateAt',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='doctor_location',
            old_name='updateBy',
            new_name='updatedBy',
        ),
    ]
