# Generated by Django 3.2.6 on 2021-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210901_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializations',
            name='specialization',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
