# Generated by Django 3.2.6 on 2021-10-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_specializations_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.specializations'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
