# Generated by Django 3.2.6 on 2021-10-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211013_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('category_image', models.FileField(default=None, upload_to='categoryimages')),
                ('status', models.IntegerField(default=1)),
                ('createdBy', models.CharField(default='system', max_length=30)),
                ('updatedBy', models.CharField(default='system', max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
