# Generated by Django 3.2.6 on 2021-10-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
