# Generated by Django 3.2.6 on 2021-10-18 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_categories_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('product_image', models.FileField(null=True, upload_to='productimages')),
                ('product_stock', models.IntegerField(null=True)),
                ('product_price', models.FloatField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('createdBy', models.CharField(default='system', max_length=30)),
                ('updatedBy', models.CharField(default='system', max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categories')),
            ],
        ),
    ]
