# Generated by Django 3.2.6 on 2021-10-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.pharmacy'),
            preserve_default=False,
        ),
    ]
