# Generated by Django 3.2.6 on 2021-10-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_product_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pharmacy'),
        ),
    ]
