# Generated by Django 3.2.5 on 2021-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20211027_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
